name: slack-notification

on:
  pull_request:
    types: [opened]

jobs:
  slack-notifications:
    name: Sends a message to Slack when a pull request is opened
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}
    steps:
      - name: Post to Slack (v2)
        uses: slackapi/slack-github-action@v2
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: "C09LYQ1BHDJ"
            text: "*New PR waiting for review:* <${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}>"
            blocks:
              - type: section
                text:
                  type: mrkdwn
                  text: "*New PR waiting for review:*\n<${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}>"
              - type: section
                fields:
                  - type: mrkdwn
                    text: "*Opened by:*\n${{ github.event.pull_request.user.login }}"
